image: python:3.5

cache:
  paths:
    - /root/.cache

before_script:
  - pip install tox

flake8:
  script:
    - tox -e flake8

pylint:
  script:
    - tox -e pylint

py35:
  script:
    - apt-get update && apt-get install -y lame libmp3lame-dev libvorbis-dev
    - tox -e py35-cover
