image: python:3.5

cache:
  paths:
    - .pip
    - .tox

before_script:
  - pip --cache-dir=.pip install tox

flake8:
  script:
    - tox -e flake8

pylint:
  script:
    - tox -e pylint

py35:
  script:
    - apt-get update &&
      apt-get install -y lame libmp3lame-dev libmpg123-dev libvorbis-dev
    - tox -e py35-cover
  coverage: '/TOTAL\s+(?:\d+\s+){4}(\d+\%)/'
