# sync_music - Sync music library to external device
# Copyright (C) 2013-2018 Christian Fetzer
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

# Tox configuration file

[gh]
python =
    3.9 = 3.9
    3.10 = 3.10
    3.11 = 3.11
    3.12 = 3.12
    3.13 = 3.13

[tox]
envlist = py39,py310,py311,py312,py313

[testenv]
deps = pytest-cov
       pytest-mock
commands = pytest {posargs} --cov=sync_music --cov-branch \
                            --cov-report=term-missing --cov-fail-under=100
